spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_5992fc318c5100e?reconnect=true&user=b19e5827afd41e&password=9468f7f6&useUnicode=true&characterEncoding=UTF-8
    username: b19e5827afd41e
    password: 9468f7f6
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    #database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: warn
    com.lrm: info
  file: log/patisserie-pro.log
server:
  port: 8081
  