spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: pro


  http:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
    - classpath:/META-INF/resources/,classpath:/resources/, classpath:static/, classpath:/public/,file:static/


