spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: dev

  http:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      #location: /Users/amber/mrtsuopat/src/main/resources/static/image/
  #resources:
   # static-locations:
    #- classpath:/META-INF/resources/,classpath:static/,file:static/,classpath:/resources/,file:{http.multipart.location}   
  mvc:
    static-path-pattern: /**