spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mrtsuo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1105dddd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
logging:
  level:
    root: info
    com.mrtsuo: debug
  file: log/patisserie-dev.log
server:
  port: ${PORT:9527}