spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/mrtsuo?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_5992fc318c5100e?reconnect=true
    username: b19e5827afd41e
    password: 9468f7f6
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    #database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: warn
    com.lrm: info
  file: log/patisserie-pro.log
server:
  port: ${PORT:8081}
  #port: 8081
  