spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: dev

  http:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      location: /Users/amber/uploadImage/
      