spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/mrtsuo?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://b8e359ab48ae13:e197153c@us-cdbr-east-02.cleardb.com/heroku_e88d98a3e4f5f72?reconnect=true
    username: b8e359ab48ae13
    password: e197153c
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: warn
    com.lrm: info
  file: log/patisserie-pro.log
server:
  port: ${PORT:8081}
  