uploadpic:
   path: /Users/amber/mrtsuopat/target/uploadpic/
  #path: /Users/amber/uploadpic/
  
spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
    cache: false
  profiles:
    active: pro


  http:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
      
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
    - file:${uploadpic.path}
     
