spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/mrtsuo?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_6ec3f736ad970fe?reconnect=true
    username: b4ca037148d47c
    password: cf68c13a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: warn
    com.lrm: info
  file: log/patisserie-pro.log
server:
  port: ${PORT:8081}
  